language: node_js
sudo: required
node_js:
- 7.9.0
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- npm install -g hexo-cli
install:
- npm install
- npm install hexo-deployer-git --save
script:
- hexo generate
after_script:
- openssl aes-256-cbc -K $encrypted_89ed460c81a8_key -iv $encrypted_89ed460c81a8_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config user.name "blademainer"
- git config user.email "blademainer@gmail.com"
- sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
- sed -i "s/{{baidu_token}}/${BAIDU_TOKEN}/g" ./_config.yml
- hexo deploy
env:
  global:
    secure: ee84BM562T/0QMRE2Zf9nJocHQwrFRpUjUC+tcPe3Rcmz+/LKt72phRhxoRuStHtuE7EvzvMQPlkeWkMqjw5vQPWwnWbhsNuvT8cUmuWJhjQCTJKBbviVv/SUBvo2niBS9XGYVMG51HortYC89DqKDAi+Q4kBftU7CEEzgNLgB1jkjMSvGxMYEbT0i7RpZo8qQ+ijjr+CYf6yxonFxCUJrqdBvanbkRdUifQvxXL1ao3tz9OkqdtrK6iVBpC3J5xhEQn10/ssPlOZTOln8YimHCVQXxw7sTau4LzWUCvmFU+3ATzPtjz+YnSjLalaDOnLGI8srjGRLOgsBK/0voagQ0DZ0FDQLgjxxTbqKtWSSde1JeafsptsorhA2VGwGQrx7JskBgBGKa0j7TcXm3XQzFlDP1hkDVjWTLoUxhcWHVWwoacMAgbLLxY9UYjcMpTCN3Kp/p0ZPqx92bO6DqqG4lydgmQEPO2IyB5IdZP7rQC04+AIpSiUyjBX/8+u2TZVQKw7uHWVRMl+irjer8IaH48rBgbs7280zt2N+N+3kk1+CzdOqAu7uFpSznEVVPvR3LjQbn/mrmaCqW+PcQVXKkc3oaD9cCt4UjKph4qTns38ePrEePUNWNIXuJH4Gp0baOf5WEXCReACbf7zvAkQVeqyQ/jrXD19PzNZGMqzU0=
