language: node_js
sudo: required
node_js:
- 7.9.0
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- npm install -g hexo-cli
install:
- npm install
- npm install hexo-deployer-git --save
script:
- sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
- sed -i "s/{{baidu_token}}/${BAIDU_TOKEN}/g" ./_config.yml
- sed -i "s/{{QINIU_ACCESS_KEY}}/${QINIU_ACCESS_KEY}/g" ./_config.yml
- sed -i "s/{{QINIU_SECRET_KEY}}/${QINIU_SECRET_KEY}/g" ./_config.yml
- hexo generate
after_script:
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config user.name "blademainer"
- git config user.email "blademainer@gmail.com"
- hexo deploy
env:
  global:
  - secure: ee84BM562T/0QMRE2Zf9nJocHQwrFRpUjUC+tcPe3Rcmz+/LKt72phRhxoRuStHtuE7EvzvMQPlkeWkMqjw5vQPWwnWbhsNuvT8cUmuWJhjQCTJKBbviVv/SUBvo2niBS9XGYVMG51HortYC89DqKDAi+Q4kBftU7CEEzgNLgB1jkjMSvGxMYEbT0i7RpZo8qQ+ijjr+CYf6yxonFxCUJrqdBvanbkRdUifQvxXL1ao3tz9OkqdtrK6iVBpC3J5xhEQn10/ssPlOZTOln8YimHCVQXxw7sTau4LzWUCvmFU+3ATzPtjz+YnSjLalaDOnLGI8srjGRLOgsBK/0voagQ0DZ0FDQLgjxxTbqKtWSSde1JeafsptsorhA2VGwGQrx7JskBgBGKa0j7TcXm3XQzFlDP1hkDVjWTLoUxhcWHVWwoacMAgbLLxY9UYjcMpTCN3Kp/p0ZPqx92bO6DqqG4lydgmQEPO2IyB5IdZP7rQC04+AIpSiUyjBX/8+u2TZVQKw7uHWVRMl+irjer8IaH48rBgbs7280zt2N+N+3kk1+CzdOqAu7uFpSznEVVPvR3LjQbn/mrmaCqW+PcQVXKkc3oaD9cCt4UjKph4qTns38ePrEePUNWNIXuJH4Gp0baOf5WEXCReACbf7zvAkQVeqyQ/jrXD19PzNZGMqzU0=
  - secure: OT9Vrn5lA6MPjr3xR8KvKIKzFdf19+SpfKx4aHJ3pYGbeaTsMC7jl5Lc5PKm5fyqw4UdkQT24dcpvRqax53i0BWk/M7sSZT6WgsjBdup/dmN2s9pg0P9qkHyxwICjOjIdBowLIAspgKJwcSj2o3V+7Ff1gvuIOUfe7N/9ay5OVdpWxr4MMUxFKv+Eba5dSS749f3tq62kfL2M6YJVVRYTZE4oEt8XSiHd10XAiblOiCAKZfOeO2JNFE8TkTpXyQjnHgyrJMSpgbtnhGew+Gl5PSFbOGudout600lqnkh36pTeSNLfn5LLdsTYsEU9qQl91DYl5pBvaY9BA40VDCt5Q174JMmnsAFUbAjQACIDur1sgvhFizIjHOL9DBbN/01r3wVhTfyLQd+iehdbmdQMBBDXVRCkYndzqnwZVDeNJJ1fzctrc859dnZ1GQopPVuIz2Zk5uoXftHvBmyfVYFhQgRS26Wz6UBQkVpIi5YCX3iV69nORT2v3hzwKgxZaKlXp+ljPV5GOOY7R1TgtEuNrf7UHcwbIM6w66fnAZhnRhCa9/JKOdLyfpWf+IrHbAiCcVoOUmL8moxxF2GynIwicQz7PTwWUktJ1ylDuRbyLB45f9d+hy1u72w445Vllgng0VANyY//k9Qm5+8YwEqRtTAZZEheQtSOl7C9GXbDuA=
  - secure: ioQ3vulag7Cv/GVFO720tNUgTEf1+lwP0UmCeNzHHsE+jXrSqb/IWUfaCBAMKXLQLDG/w8qyMAv4GTPMIGPpkh8Dpeyw/Mu9w0kNGaPQarwnH99uy1btzsxoGyOh4oouJN4G29GJmVgM1fLCmMtviFkRzzvp7pMvRCSRr0CQoIK/Dml4xEzwMwKf51XscQL6o3MCynd8mfbv841NJYDO/aiempXE+G2jQ8XtDnRAXO4yYVXs1UDO1H6NbJRmcbX2FRYrsYNd/wlIrz3/y6N/7q3yDHmutnpeL/Pger6qK+NH7eg6/jA8sgE5V0mxnvPXVwZV2wNYMknWGakpF+Kg+Z4tVzjI8qhbHwJKuIFu29c1NyzeU9kKiDNmmLEVEoIsrCQN6rb2nsZ99R1XiDgT05kX5V/tOHm2vJC7e26DTGSNWCzjz2aOZeObelKY/7VU5FHIkQGN7a8Gz6AuzaignqSzKeFcOfcWyGRHNhXH53t747u5sJFX21T48nCcfp45loK7u6pTP7tleGmufSylpiLdDWBLOxLQEx9zzyNyp7vnn3IiUt3U2V+WIZcoh8WhU84+yOm39vMyVJr012yhHlNBh8tFAU3Xjw7/okNfVD/sKBxs4vIWV0k8dO5HEzmEQnzGNhkgTMUMQptNAyZaR0rmk061nQrd+QRFsrjH4l8=
  - secure: D+RXDcbGz5P0z7jAO5dbI8i67WFF2Rrmshk+J99LC3v67NXTc4EOxAArm3moTLUtbcbigwvM2JR6ei81JBaBjoRpfh9uQkWJmV1h5iWYGMCPQA9Bpir0eJDTkqTXU2Yzj25C+J5xUa/5GEkgTQZUJuryD+c3Q8ajwpXNKQ+6qr5p/5uuQCMPdWAZ5PGw/P1JslfqUKjCdo6NkaTzeUhHzelFIBigkUTDJk6C7RK7IZX7Y4eXUMXMnQEUr3WyvZmEryIefhI8EueA7NmZ1Ui3S3Unka/W7/cjuNJWVA3W7/AXhk8FgSqF4uD35oTBLobZqjh+gf0mZycG5PTIrIVF3WFWVleDPxqNTnMbAitjQqNl9EGW4KR9RDOvGPklfWVtpeB6ID9AASuT0J1ZO2M8bnqp6zSBW1b7YlPtVZO6bbUispqJ66fSjIcLLw0eelvHHITwXSFWFZ8W1AmhFwB/weR8lc0I2t2RIWm3bFb4YoPHUxyyLO86zAwNBOQVmco789V4vhNuHAGihY7TQV5MSvE0LP+AuAVgDavf+jf1eJ6WJO7XFGVt65+imCdpLsf9J9HOFIeHh8To9fcio8+fPgqCsyY1MDOhe796H5HG/uJX1t8r0dxdtCHJwv5vGzE4KlTl0LL7NqpW1hg6cVAoAElFV+y11CL7dyuiLpT2zOQ=
